# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [14]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.8491, 0.6260, 0.0977, 0.2579, 0.7300, 0.2676, 0.0601],
        [0.7219, 0.7796, 0.3879, 0.8131, 0.5098, 0.7262, 0.5336],
        [0.0997, 0.5698, 0.9738, 0.8374, 0.6648, 0.1986, 0.4911],
        [0.7258, 0.2842, 0.2934, 0.4436, 0.2116, 0.3719, 0.7218],
        [0.2457, 0.3415, 0.6314, 0.2870, 0.1314, 0.9273, 0.4154],
        [0.5574, 0.5014, 0.1123, 0.8740, 0.6480, 0.0561, 0.2258],
        [0.8284, 0.1531, 0.5551, 0.7991, 0.1019, 0.1975, 0.4656]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [22]:
# Create another random tensor
multiply1 = torch.rand(1,7)
multiply2 = torch.rand(1,7).T

mul = torch.mm(multiply1, multiply2)
mul
# Perform matrix multiplication


tensor([[2.2444]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [55]:
# Set manual seed
SEED = 0


# Create two random tensors
torch.manual_seed(SEED)
tenA = torch.rand(1,7)
torch.manual_seed(SEED)
tenB = torch.rand(1,7).T


# Matrix multiply tensors
print(torch.matmul(tenA,tenB))

tensor([[1.5985]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [34]:
# Set random seed on the GPU
SEED = 1234

torch.manual_seed(SEED)
if torch.cuda.is_available():
  torch.cuda.manual_seed(SEED)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [41]:
# Set random seed
seed = 1234


# Check for access to GPU
if torch.cuda.is_available:
  device = "cuda"
else:
   device = "cpu"
# Create two random tensors on GPU
torch.manual_seed(seed)
tens1 = torch.rand(2,3)
ten1 = tens1.to(device)
tens2 = torch.rand(2,3)
ten2 = tens2.to(device)
print(device)
print(ten1)
print(ten2)


cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [45]:
# Perform matmul on tensor_A and tensor_B
size = torch.mm(ten1,ten2.T)
size.shape
size



tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [48]:
# Find max
max = torch.max(size)
# Find min
min = torch.min(size)
print(max)
print(min)


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [50]:
# Find arg max
print(torch.argmax(size))
# Find arg min
print(torch.argmin(size))


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [53]:
# Set seed
SEED = 7
# Create random tensor
torch.manual_seed(SEED)
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
torch.manual_seed(SEED)
squeezed = tensor.squeeze()


# Print out tensors and their shapes
print(tensor, tensor.shape)
print(squeezed, squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
